Repository onulstore/Onulstore-FE, pull requests merged in 2022-09, with the labels that each got.

#3 공통 컴포넌트 제작(Button, HeaderBar, Loading)
  src/components/Icons/index.tsx
  src/components/ui/LargeBtn/index.tsx
  src/components/ui/LargeBtn/style.ts
  src/components/ui/Loading/index.tsx
  src/components/ui/Loading/style.ts
  src/components/ui/SmallBtn/index.tsx
  src/components/ui/SmallBtn/style.ts
  src/components/ui/navbar/HeaderBar/index.tsx
  src/components/ui/navbar/HeaderBar/style.ts
  src/utils/constants.ts
Labels: 🙏 feedback

#7 User input #2
  src/components/user/FormInput/index.tsx
  src/components/user/FormInput/style.ts
Labels: ✨ Feature, 🙏 feedback, 🎨 HTML & CSS

#10 Home swiper #4
  package-lock.json
  package.json
  src/assets/data.json
  src/components/home/Swiper/index.tsx
  src/components/home/Swiper/style.ts
Labels: ✨ Feature, 🎨 HTML & CSS

#12 Item #5
  src/App.tsx
  src/assets/dumyBg.png
  src/components/Icons/index.tsx
  src/components/item/CustomSelectBox/FilterSelectBox/index.tsx
  src/components/item/CustomSelectBox/FilterSelectBox/style.ts
  src/components/item/CustomSelectBox/index.tsx
  src/components/item/ItemAlbum/index.tsx
  src/components/item/ItemAlbum/style.ts
  src/components/item/ItemFilterBar/index.tsx
  src/components/item/ItemFilterBar/style.ts
  src/components/item/LargeCategoryModal/style.ts
  src/components/item/NowPositionBar/index.tsx
  src/components/item/NowPositionBar/style.ts
  src/components/item/SmallCategoryModal/index.tsx
  src/components/layout/index.ts
  src/components/ui/navbar/HeaderBar/index.tsx
  src/pages/ItemDetail.tsx
  src/pages/ItemDetail/index.tsx
  src/pages/Items.tsx
  src/pages/Items/index.tsx
  src/pages/Items/style.ts
  src/store/hooks/index.ts
  src/store/slices/itemSlice.ts
  src/utils/Api/dumy/dumyApi.ts
  src/utils/Api/dumy/index.ts
  src/utils/Api/index.ts
  src/utils/constants.ts
Labels: 📬 API, ✨ Feature, 🙏 feedback, 🎨 HTML & CSS

#18 User input edit #15
  src/components/user/FormInput/style.ts
Labels: 🎨 HTML & CSS

#16 Sign up #9
  package-lock.json
  src/App.tsx
  src/components/user/SignUpForm/index.tsx
  src/components/user/SignUpForm/style.ts
  src/pages/SignUp/index.tsx
  src/utils/constants.ts
Labels: 🎨 HTML & CSS

#20 Refactor header bar #11
  src/components/ui/navbar/HeaderBar/index.tsx
  src/components/ui/navbar/HeaderBar/style.ts
Labels: 🎨 HTML & CSS, 🔨 Refactor

#25 design: color Settings
  src/style/styled.d.ts
  src/style/theme.ts
Labels: 🎨 HTML & CSS

#21 Item #5
  package-lock.json
  package.json
  src/App.tsx
  src/components/Icons/index.tsx
  src/components/item/ItemAlbum/index.tsx
  src/components/itemDetail/DetailNavigation/index.tsx
  src/components/itemDetail/DetailNavigation/style.ts
  src/components/ui/PurchaseBtn/index.tsx
  src/components/ui/PurchaseBtn/style.ts
  src/components/ui/WishListBtn/index.tsx
  src/components/ui/WishListBtn/style.ts
  src/pages/ItemDetail/DetailInfo/ItemInfo/index.tsx
  src/pages/ItemDetail/DetailInfo/ItemInfo/style.ts
  src/pages/ItemDetail/DetailInfo/OrderGuide/index.tsx
  src/pages/ItemDetail/DetailInfo/OrderGuide/style.ts
  src/pages/ItemDetail/DetailInfo/Q&AInfo/index.tsx
  src/pages/ItemDetail/DetailInfo/Q&AInfo/style.ts
  src/pages/ItemDetail/DetailInfo/ReviewInfo/index.tsx
  src/pages/ItemDetail/DetailInfo/ReviewInfo/style.ts
  src/pages/ItemDetail/DetailInfo/SimilarItem/index.tsx
  src/pages/ItemDetail/DetailInfo/SimilarItem/style.ts
  src/pages/ItemDetail/index.tsx
  src/pages/ItemDetail/style.ts
  src/pages/Items/index.tsx
  src/store/slices/itemSlice.ts
  src/utils/constants.ts
Labels: 🎨 HTML & CSS

#17 Home nav bar swiper #13
  src/components/home/Swiper/index.tsx
  src/components/home/Swiper/style.ts
Labels: ✨ Feature, 🎨 HTML & CSS

#22 Home today countdown #19
  src/components/home/TodayTimer/index.tsx
  src/components/home/TodayTimer/style.ts
  src/store/hooks/useTodayCountdown.ts
Labels: ✨ Feature, 🎨 HTML & CSS
