Repository onulstore/Onulstore-FE, pull requests merged in 2022-10, with the labels that each got.

#36 design: lightMidGrey 컬러 추가
  src/style/styled.d.ts
  src/style/theme.ts
Labels: 🎨 HTML & CSS

#37 design: main 컬러 타입 지정
  src/style/styled.d.ts
Labels: 🎨 HTML & CSS

#26 Home date #23
  src/components/home/Date/getDate.ts
  src/components/home/Date/index.tsx
  src/components/home/Date/style.ts
  src/components/home/home.d.ts
  src/components/home/index.tsx
Labels: ✨ Feature, 🎨 HTML & CSS

#32 Item #5
  src/App.tsx
  src/components/Icons/index.tsx
  src/components/item/ItemFilterBar/index.tsx
  src/components/item/LargeCategoryModal/style.ts
  src/components/itemDetail/AddWishListModal/index.tsx
  src/components/itemDetail/AddWishListModal/style.ts
  src/components/itemDetail/OrderGuide/DeliveryGuide/index.tsx
  src/components/itemDetail/OrderGuide/DeliveryGuide/style.ts
  src/components/itemDetail/OrderGuide/OrderGuideTitle/index.tsx
  src/components/itemDetail/OrderGuide/OrderGuideTitle/style.ts
  src/components/itemDetail/OrderGuide/PaymentGuide/index.tsx
  src/components/itemDetail/OrderGuide/PaymentGuide/style.ts
  src/components/itemDetail/OrderGuide/RefundGuide/index.tsx
  src/components/itemDetail/OrderGuide/RefundGuide/style.ts
  src/components/ui/navbar/HeaderBar/index.tsx
  src/pages/Cart.tsx
  src/pages/Home.tsx
  src/pages/ItemDetail/DetailInfo/OrderGuide/index.tsx
  src/pages/ItemDetail/DetailInfo/OrderGuide/style.ts
  src/pages/ItemDetail/index.tsx
  src/pages/Items/index.tsx
  src/pages/NotFound.tsx
  src/pages/Review.tsx
  src/utils/Api/dumy/index.ts
  src/utils/constants.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 HTML & CSS, 🔨 Refactor

#33 Sign in #14
  src/App.tsx
  src/components/Icons/index.tsx
  src/components/user/SignInForm/index.tsx
  src/components/user/SignInForm/style.ts
  src/components/user/SignUpForm/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignIn/style.ts
  src/utils/constants.ts
Labels: 🎨 HTML & CSS

#42 Item #5
  src/App.tsx
  src/components/payment/PaymentForm/index.tsx
  src/components/payment/PaymentForm/style.ts
  src/components/payment/index.tsx
  src/components/ui/CommonBlackBtn/index.tsx
  src/components/ui/CommonBlackBtn/style.ts
  src/components/ui/PurchaseBtn/index.tsx
  src/components/ui/navbar/HeaderBar/index.tsx
  src/pages/ItemDetail/index.tsx
  src/pages/Payment/index.tsx
  src/pages/Payment/style.ts
  src/store/hooks/index.ts
  src/store/slices/itemSlice.ts
  src/utils/Api/dumy/dumyApi.ts
Labels: 🐞 BugFix, 📬 API, ✨ Feature, 🎨 HTML & CSS, 🔨 Refactor

#43 UI bottom tab bar #31
  src/App.tsx
  src/components/Icons/index.tsx
  src/components/ui/navbar/BottomTabBr/index.tsx
  src/components/ui/navbar/BottomTabBr/style.ts
Labels: ✨ Feature, 🎨 HTML & CSS

#44 UI bottom tab bar menu #41
  src/components/Icons/index.tsx
  src/components/ui/navbar/Menu/NavMenu/index.tsx
  src/components/ui/navbar/Menu/NavMenu/style.ts
  src/components/ui/navbar/Menu/UserInfoIconNavBar/index.tsx
  src/components/ui/navbar/Menu/UserInfoIconNavBar/style.ts
  src/components/ui/navbar/Menu/UserNameContainer/index.tsx
  src/components/ui/navbar/Menu/UserNameContainer/style.ts
  src/components/ui/navbar/Menu/index.tsx
  src/components/ui/navbar/Menu/style.ts
Labels: ✨ Feature, 🎨 HTML & CSS

#55 Refactor scroll nav bar #45
  src/components/home/ScrollNavBar/index.tsx
  src/components/home/ScrollNavBar/style.ts
  src/components/home/Swiper/index.tsx
Labels: 🎨 HTML & CSS, 🔨 Refactor

#58 Non member #52
  src/App.tsx
  src/pages/NonMember/index.tsx
  src/pages/NonMember/style.ts
Labels: ✨ Feature, 🎨 HTML & CSS

#60 Home just for today swiper #54
  src/assets/images/home_banner_img_1.png
  src/assets/images/home_banner_img_2.png
  src/assets/images/home_banner_img_3.png
  src/assets/images/home_banner_img_4.png
  src/assets/images/today_thumbnail_1.png
  src/assets/images/today_thumbnail_2.png
  src/components/home/Swiper/index.tsx
  src/components/home/Swiper/style.ts
  src/components/home/TodayTimerProgressBar/style.ts
  src/utils/constants.ts
Labels: ✨ Feature, 🎨 HTML & CSS, 🔨 Refactor

#69 Item #5
  package-lock.json
  package.json
  src/App.tsx
  src/components/Icons/index.tsx
  src/components/item/ItemAlbum/index.tsx
  src/components/item/ItemAlbum/style.ts
  src/components/payment/PaymentForm/index.tsx
  src/components/review/uploadedImg/index.tsx
  src/components/review/uploadedImg/style.ts
  src/components/review/writtenReview/index.tsx
  src/components/review/writtenReview/style.ts
  src/components/ui/Loading/style.ts
  src/pages/ItemDetail/DetailInfo/ReviewInfo/index.tsx
  src/pages/ItemDetail/DetailInfo/ReviewInfo/style.ts
  src/pages/ItemDetail/index.tsx
  src/pages/Items/index.tsx
  src/pages/Review/index.tsx
  src/pages/Review/style.ts
  src/store/hooks/index.ts
  src/store/slices/itemSlice.ts
  src/store/slices/reviewSlice.ts
  src/store/slices/rootReducer.ts
  src/utils/Api/dumy/dumyApi.ts
  src/utils/Api/dumy/index.ts
  src/utils/Api/index.ts
  src/utils/Api/itemApi.ts
  src/utils/Api/reviewApi.ts
Labels: 📬 API, ✨ Feature, 🎨 HTML & CSS, 🔨 Refactor

#82 Auth api #68
  src/App.tsx
  src/components/routes/PrivataRoutes/index.tsx
  src/components/user/SignInForm/index.tsx
  src/components/user/SignUpForm/index.tsx
  src/pages/SignIn/index.tsx
  src/store/slices/rootReducer.ts
  src/store/slices/userSlice.ts
  src/utils/Api/index.ts
  src/utils/Api/userApi.ts
  src/utils/authUtils.tsx
  src/utils/constants.ts
Labels: 📬 API, ✨ Feature

#79 Search #75
  src/App.tsx
  src/components/search/SearchHeader/index.tsx
  src/components/search/SearchHeader/style.ts
  src/components/search/SearchResults/index.tsx
  src/components/search/SearchResults/style.ts
  src/components/search/SearchedKeywords/index.tsx
  src/components/search/SearchedKeywords/style.ts
  src/components/search/hooks.ts
  src/components/ui/navbar/HeaderBar/index.tsx
  src/pages/Search/index.tsx
  src/pages/Search/style.ts
Labels: ✨ Feature, 🎨 HTML & CSS

#87 #81 feat: SetHeaderBar, SetBottomTabBar 하이 오더 컴포넌트 구현
  src/App.tsx
  src/pages/Cart/index.tsx
  src/pages/FindEmail/index.tsx
  src/pages/Home/index.tsx
  src/pages/Items/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/NonMember/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/Payment/index.tsx
  src/pages/QnA/index.tsx
  src/pages/Recent/index.tsx
  src/pages/Review/index.tsx
  src/pages/Search/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/index.tsx
  src/pages/Today/index.tsx
  src/pages/WeLike/index.tsx
  src/pages/WishList/index.tsx
  src/utils/HOC/SetBottomBar.tsx
  src/utils/HOC/SetHeaderBar.tsx
Labels: ✨ Feature

#90 Refactor page name #89
  src/App.tsx
  src/utils/constants.ts
Labels: 🔨 Refactor

#77 Item #5
  src/App.tsx
  src/components/QnA/AnswerBox/index.tsx
  src/components/QnA/AnswerBox/style.ts
  src/components/QnA/QnABox/index.tsx
  src/components/QnA/QnABox/style.ts
  src/components/QnA/QuestionBox/index.tsx
  src/components/QnA/QuestionBox/style.ts
  src/components/item/CustomSelectBox/FilterSelectBox/index.tsx
  src/components/item/CustomSelectBox/index.tsx
  src/components/item/ItemAlbum/index.tsx
  src/components/item/ItemAlbum/style.ts
  src/components/item/SmallCategoryModal/index.tsx
  src/components/item/SmallCategoryModal/style.ts
  src/components/layout/index.ts
  src/components/ui/navbar/BottomTabBr/style.ts
  src/components/ui/navbar/index.tsx
  src/components/user/index.tsx
  src/pages/Cart/index.tsx
  src/pages/ItemDetail/DetailInfo/QnAInfo/index.tsx
  src/pages/ItemDetail/DetailInfo/QnAInfo/style.ts
  src/pages/ItemDetail/DetailInfo/ReviewInfo/style.ts
  src/pages/ItemDetail/index.tsx
  src/pages/Items/index.tsx
  src/pages/Items/style.ts
  src/pages/QnA/index.tsx
  src/pages/QnA/style.ts
  src/pages/Review/index.tsx
  src/pages/WishList/index.tsx
  src/store/hooks/index.ts
  src/store/slices/QnASlice.ts
  src/store/slices/cartSlice.ts
  src/store/slices/rootReducer.ts
  src/utils/Api/QnA_Api.ts
  src/utils/Api/cartApi.ts
  src/utils/Api/index.ts
  src/utils/Api/itemApi.ts
Labels: 📬 API, ✨ Feature, 🎨 HTML & CSS, 🔨 Refactor

#94 Item detail edit #93
  src/components/item/ItemAlbum/index.tsx
  src/components/item/ItemAlbum/style.ts
  src/pages/Items/index.tsx
Labels: 🔨 Refactor

#96 Layout edit #95
  src/components/layout/index.ts
  src/style/global.ts
Labels: 🎨 HTML & CSS, 🔨 Refactor

#102 Px edit #101
  src/components/Icons/index.tsx
  src/components/user/FormInput/style.ts
  src/components/user/MyHistoryDetail/style.ts
  src/components/user/MyInfoForm/style.ts
  src/components/user/MyOrder/style.ts
  src/components/user/MyOrderCancel/style.ts
  src/components/user/MyOrderDetail/style.ts
  src/components/user/SignUpForm/style.ts
  src/pages/FindEmail/style.ts
  src/pages/NonMember/style.ts
  src/pages/SignIn/style.ts
  src/utils/Api/index.ts
Labels: 🎨 HTML & CSS

#103 #95 design: 반응형에 padding-bottom 추가
  src/components/layout/index.ts
Labels: 🎨 HTML & CSS

#100 My page api #78
  src/components/user/MyHistory/index.tsx
  src/components/user/MyInfo/index.tsx
  src/components/user/MyInfo/style.ts
  src/components/user/MyInfoForm/index.tsx
  src/components/user/MyInfoForm/style.ts
  src/components/user/SignInForm/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyPage/style.ts
  src/store/hooks/index.ts
  src/utils/authUtils.tsx
Labels: 📬 API, ✨ Feature

#109 Auth api #68
  src/main.tsx
  src/utils/Api/index.ts
Labels: ✨ Feature

#97 Today #91
  src/App.tsx
  src/assets/images/today_banner_img.png
  src/components/home/Swiper/index.tsx
  src/components/home/Swiper/style.ts
  src/components/today/TodayBanner/index.tsx
  src/components/today/TodayBanner/style.ts
  src/components/today/TodayItems/index.tsx
  src/components/today/TodayItems/style.ts
  src/components/ui/SmallBtn/index.tsx
  src/components/ui/SmallBtn/style.ts
  src/pages/Today/index.tsx
  src/utils/constants.ts
  src/utils/test_constants.ts
Labels: ✨ Feature, 🎨 HTML & CSS

#111 We like magazine #98
  src/App.tsx
  src/assets/images/we-like_magazine_1.png
  src/assets/images/we-like_magazine_2.png
  src/assets/images/we-like_magazine_3.png
  src/components/weLike/Magazine/index.tsx
  src/components/weLike/MagazineList/index.tsx
  src/components/weLike/MagazineList/style.ts
  src/components/weLike/WeLikeNavBar/index.tsx
  src/components/weLike/WeLikeNavBar/style.ts
  src/pages/WeLike/Magazine/index.tsx
  src/utils/constants.ts
  src/utils/test_constants.ts
Labels: ✨ Feature, 🎨 HTML & CSS

#118 Test 발표용 배포
  netlify.toml
  src/components/ui/navbar/Menu/UserNameContainer/index.tsx
  src/components/ui/navbar/Menu/UserNameContainer/style.ts
  src/pages/SignIn/index.tsx
  src/utils/Api/index.ts
Labels: 🌏 Deploy

#120 Scroll to top #119
  src/components/common/ScrollToTop/index.tsx
  src/main.tsx
Labels: ✨ Feature

#127 Curations #125
  src/store/hooks/index.ts
  src/store/slices/curationSlice.ts
  src/store/slices/rootReducer.ts
  src/utils/Api/curationApi.ts
Labels: 📬 API

#132 #128 feat: useSearchSlice 구현
  src/store/hooks/index.ts
Labels: ✨ Feature

#135 #134 config: 메타태그 설정
  index.html
  src/assets/images/favicon.png
  src/assets/images/meta-image.png
Labels: 🎨 HTML & CSS

#136 Auth api #68
  src/utils/Api/index.ts
Labels: 🔨 Refactor

#138 Search total result value bar #131
  src/components/search/SearchResults/index.tsx
  src/components/search/TotalResultValueBar/index.tsx
  src/components/search/TotalResultValueBar/style.ts
  src/store/slices/searchSlice.ts
Labels: ✨ Feature, 🎨 HTML & CSS

#140 Notice #139
  src/components/home/Swiper/index.tsx
  src/pages/Home/index.tsx
  src/store/hooks/index.ts
  src/store/slices/noticeSlice.ts
  src/store/slices/rootReducer.ts
  src/utils/Api/noticeApi.ts
Labels: 📬 API, ✨ Feature
